#!/bin/bash

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
BASHDIR=$ROOTDIR/bash

command="${1: }"
arguments="${@:2}"

help() {
    echo -e "
    dotfiles installation

    Usage: ./install <os>

    os:
      win             Git bash in Windows
      mac             MacOS
    "
}

case ${command} in
    -h)
        help
        ;;
    --help)
        help
        ;;
    help)
        help
        ;;
    "")
        help
        ;;
    win)
        cd $BASHDIR && ./win-setup $arguments
        ;;
    mac)
        cd $BASHDIR && ./mac-setup $arguments
        ;;
    *)
        echo ""
        echo "Error. Unknown command."
        help
        ;;
esac





