#!/bin/bash

# Installs the contents of the bin folder to the machine user bin folder (/usr/local/bin)

echo "Installing scripts."

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ ! -d "$HOME" ]; then
    echo "HOME dir did not exist. Something is wrong. Giving up script install."
fi

SRC="$ROOTDIR/bin"
DEST="$HOME/bin"

mkdir -p $DEST

cp -rv $SRC/* $DEST/

echo 'PATH="${PATH}:~/bin"' >> ~/.bashrc