#!/bin/bash

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
THEME="pure"

echo "Installing bash-it."

rm ~/.bashrc &> /dev/null
rm ~/.bash_profile &> /dev/null

git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it 2> /dev/null
cd ~/.bash_it
git pull &> /dev/null

./install.sh --silent

if [ -f ~/.bash_profile ]; then
    mv ~/.bash_profile ~/.bashrc
fi

cp $ROOTDIR/.bash_profile ~/

sed -i.backup 's/bobby/pure/' ~/.bashrc
rm ~/.bashrc.backup &> /dev/null

echo "Sourcing the new file."
source ~/.bashrc

echo "Setting up bash-it."

bash-it enable alias curl
bash-it enable alias git
bash-it enable alias npm

bash-it enable alias todo.txt-cli
bash-it enable alias tmux
bash-it enable alias vim
bash-it enable alias yarn

bash-it enable completion bash-it
bash-it enable completion docker
bash-it enable completion docker-compose
bash-it enable completion git
bash-it enable completion npm
bash-it enable completion ssh

bash-it enable plugin docker
bash-it enable plugin docker-compose
bash-it enable plugin git
bash-it enable plugin node
bash-it enable plugin ssh
bash-it enable plugin visual-studio-code

echo "Adding the editenv alias (open .environment in VS Code) to ~/.bashrc"
echo 'alias editenv="code ~/.environment && source ~/.environment"' >> ~/.bashrc

# Set a variable that can be checked to see if ~/.bashrc already ran
echo 'export DOTFILES_INIT=true' >> ~/.bashrc

echo 'echo ".bashrc ✓"' >> ~/.bashrc

echo "Ensuring that ~/.environment exists and is sourced in .bashrc. Use this file to insert your machine specific details."
touch ~/.environment
echo 'source ~/.environment' >> ~/.bashrc

source $ROOTDIR/bin-install