#!/bin/bash

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SRCDIR=$ROOTDIR

command="${1: }"
arguments="${@:2}"

help() {
    echo -e "
    bash dotfiles installation ❤️

    Usage: ./install.sh <os>

    os:
      win             Git bash in Windows
      mac             MacOS
    "
}

case ${command} in
    -h)
        help
        ;;
    --help)
        help
        ;;
    help)
        help
        ;;
    "")
        help
        ;;
    win)
        cd $SRCDIR && ./win-setup.sh $arguments
        ;;
    mac)
        cd $SRCDIR && ./mac-setup.sh $arguments
        ;;
    *)
        echo ""
        echo "Error. Unknown command."
        help
        ;;
esac





