#!/bin/bash

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $ROOTDIR/common-setup

bash-it enable alias homebrew
bash-it enable alias homebrew-cask
bash-it enable alias osx

bash-it enable completion brew
bash-it enable completion nvm

bash-it enable plugin nvm
bash-it enable plugin osx

bash-it disable plugin sshagent

source ~/.bashrc